examples/pytorchjob.yaml, examples/tfjob.yaml, examples/xgboostjob.yaml, test-requirements.txt, tests/integration/test_charm.py, tox.ini
This PR introduces the following changes:
* tests/integration: adds integration tests
* Adds tox.ini and test-requirements.txt
* Adds examples/ with simple training jobs manifests (excluding mxnet)
> NOTE: I understand that multiple asserts in a single test is not desirable, please let me know if you've an alternative for `test_can_i_create_training_jobs`.
=> Adds integration tests, testing dependencies and tox.ini for integration testing

test-requirements.txt, tests/unit/test_charm.py, tox.ini
This PR adds unit testing for the training-operator. These commits introduce the following changes:
* tests/unit: adds unit testing for training-operator
* Test cases are divided into two groups: handlers to exercise event handlers, and helpers. Please note these test cases rely on what's defined in [PR#7](https://github.com/canonical/training-operator/pull/7)
* Mocks based on @jnsgruk's example for [charm-kubernetes-dashboard](https://github.com/jnsgruk/charm-kubernetes-dashboard/blob/8b2a7320dcc51f8a042a3eaddae583f6825eedea/tests/unit/test_charm.py)
* tox.ini: adds unit test block
Feedback is greatly appreciated
=> tests/unit: adds unit testing for training-operator

charmcraft.yaml, tests/integration/test_charm.py, tests/unit/test_charm.py
This PR introduces:
* charmcraft.yaml: removes kubectl part
* tests/: tidies up integration and unit testing
=> Clean up chores for charmcraft.yaml and tests/

src/charm.py
This change prevents the unit to be in MaintenanceStatus for an indefinitely time since no other events can correctly change the status and set resources. Also, removing it from event handlers makes more sense as it is used exclusively when creating/modifying Pebble layers.
=> src/charm.py: moves can_connect() check to _update_layer

src/charm.py
Modifying the resource creation to allow catching 403 codes,
which at the same time allows a more intelligent recovery after
a BlockedStatus by deferring the OnInstall event handler.
=> Modifies resource creation and adds defer condition 

.github/workflows/publish.yaml, .github/workflows/release.yaml
Add new release charm action. Update publish action to use `upload-charm` as the release action need the release info from that action. 
It's using the release charm action from [promote-charm branch](https://github.com/canonical/charming-actions/tree/promote-charm). This would be updated in the future to use stable version
=> release charm action

metadata.yaml, src/charm.py, tests/integration/test_charm.py
Update of https://github.com/canonical/training-operator/pull/27 according to latest Observability Team's review: removed the direct relation between prometheus and training-operator.
=> Removed prometheus-app direct relation in test

.github/workflows/integration.yaml
Change to be able to test training-operator 1.5.0 in microk8s 1.22
=> ci: pin microk8s 1.22 in integration job

CONTRIBUTING.md
Adds CONTRIBUTING.md file. It is based on the template-operator [CONTRIBUTING.md file](https://github.com/canonical/template-operator/blob/main/CONTRIBUTING.md), with instructions on how to upgrade src and resources for the operator.
=> docs: adds CONTRIBUTING.md file

test-requirements.txt
Pin python-libjuju to 3.0 to avoid CI issues
=> build: update python-libjuju pin to 3.0

metadata.yaml
bump image from training operator 1.6.0-rc.0 to 1.6.0-rc.1 for kubeflow 1.7 release
=> Upgrade image for 1.7 release

.github/workflows/integrate.yaml
to be consistent in all of our repos, use `charmed-kubernetes/actions-operator@main` in `Setup operator environment`
=> fix: use charmed-kubernetes/actions-operator@main

requirements.txt
SDI is not used in this charm, there is no need for SDI dependencies.
Fixes #83 CI.
=> build: remove all SDI dependencies

requirements.txt
SDI is not used in the charm, no installation needed.
=> [backport of 01d43b6] build: remove all SDI dependencies (#89)

src/charm.py
This adds `force=True` to app lightkube.Client.apply() calls due to issues with conflicting resources, like described [here](https://github.com/canonical/training-operator/issues/104).  This does work around the issue in #104, but likely we should keep #104 open until we have a better standard solution. 
(same as #104)
```
charmcraft pack
juju deploy training-operator --channel 1.5/stable --trust
juju refresh training-operator --path ./training-operator_ubuntu-20.04-amd64.charm  --resource training-operator-image=kubeflow/training-operator:v1-66aa635
```
=> fix: Use force on all client.apply() calls

tools/get-images.sh
Used by CVE scanning workflows and can be used to collect images URL for airgapped setup. Script is specific for track/1.i6 branch to capture all images for that branch. Branch is handled in kubeflow-ci and bundle automation using bundle file.
Summary of changes:
- Re-designed get images script to retrieve all images for current branch. Branch management is done outside of this script.
=> feat: updated get images script without branch checkout for track/1.6

requirements-integration.in, requirements-integration.txt, requirements-unit.txt, requirements.txt
Bump these package versions to avoid the issues described in https://github.com/canonical/bundle-kubeflow/issues/648.
Part of canonical/bundle-kubeflow#648
=> build: bump juju 2.9.44.0, sdi->0.7.0, pyyaml->6.0.1

.github/workflows/integrate.yaml, src/templates/auth_manifests.yaml.j2, tests/integration/profile.yaml, tests/integration/test_charm_with_profile.py, tox.ini
Adds Aggregation ClusterRoles for training-operators so the `default-editor` can get access to manage the various *Jobs the training-operator offers. This fixes #108 in `main`, thus `latest/edge`, a follow up PR will be sent to fix the issue in the `1.7/stable` channel.
Part of #108
TODO:
=> fix: add training-operator aggregation ClusterRoles

tests/integration/test_charm.py
This is a temporary patch until we migrate to Juju 3.1:
* Pin Prometheus revision when deploying from `latest` to avoid fetching recent patches of the charm which assume `juju >= 3.0.3`. Revision 137 was the last one seen working properly in our [CI integration tests](https://github.com/canonical/notebook-operators/actions/runs/5904696558/job/16017327250#step:4:212).
* Pin Grafana revision when deploying from `latest` to avoid fetching recent patches of the charm which fail to install on Juju 2.9. Revision 89 was the last one working properly in our CI integration tests.
Refs https://github.com/canonical/bundle-kubeflow/issues/688
Refs https://github.com/canonical/bundle-kubeflow/issues/690
=> fix: Pin Prometheus and Grafana revisions (#128)

lib/charms/observability_libs/v1/kubernetes_service_patch.py, src/charm.py, tests/integration/test_charm.py, tests/unit/test_charm.py
* fix: expose metrics port using kubernetes_service_patch lib
The changes introduced by this commit ensure the metrics port is exposed in the Kubernetes Service for the training-operator using the kubernetes_service_patch lib. This makes the metrics endpoint reachable from external prometheus scraper.
This commit also changes the unit tests slightly to adapt to the added service patcher.
* tests: add an assertion for checking unit is available
The test_prometheus_grafana_integration test case was doing queries to prometheus
and checking the request returned successfully and that the application name and model
was listed correctly. To make this test case more accurately, we can add an assertion that
also checks that the unit is available, this way we avoid issues like the one described in …
=> fix: expose metrics port using kubernetes_service_patch lib

lib/charms/observability_libs/v1/kubernetes_service_patch.py, src/charm.py, tests/integration/test_charm.py, tests/unit/test_charm.py
* fix: expose metrics port using kubernetes_service_patch lib
This commit ensures the metrics port is exposed in the Kubernetes Service for the training-operator using the kubernetes_service_patch lib. This makes the metrics endpoint reachable from external prometheus scraper.
This commit also changes the unit tests slightly to adapt to the added service patcher.
Part of canonical/bundle-kubeflow#564
* tests: add an assertion for checking unit is available
The test_prometheus_grafana_integration test case was doing queries to prometheus and checking the request returned successfully and that the application name and model was listed correctly. To make this test case more accurately, we can add an assertion that also checks that the unit is available, this way we avoid issues like the one …
=> fix: expose metrics port using kubernetes_service_patch lib (#151)

requirements-integration.in, requirements-integration.txt, tests/integration/test_charm.py, tests/integration/test_charm_with_profile.py
Pins dependencies in the integration tests to their corresponding channels for this release.
Ref: https://github.com/canonical/bundle-kubeflow/issues/866
This PR forward-ports the efforts in https://github.com/canonical/training-operator/pull/155 to `main`.
=> pin integration test dependencies, refactor constants in tests (#155)

charmcraft.yaml, config.yaml, metadata.yaml, src/charm.py, src/templates/deployment.yaml.j2, src/templates/rbac_manifests.yaml.j2, tests/integration/test_charm.py, tests/integration/test_charm_with_profile.py, tests/unit/test_charm.py
This commit refactors the way the training-operator is deployed, as instead of using a sidecar container that runs the workload, we are now applying the Deployment and all the Kubernetes resources required by the training-operator controller to be able to mange training resources.
We are introducing this change in preparation for the upcoming 1.8 version, as it introduces the hard dependency on a Kubernetes Secret mounted in a volume for the training-operator workload to start. For more details please refer to canonical/training-operator#159.
=> refactor: deploy the training-operator with kubernetes resources

.github/workflows/integrate.yaml
Part of canonical/bundle-kubeflow#944
=> ci: use juju 3.4/stable instead of 3.5/stable in track 1.7

lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py
part of fixing https://github.com/canonical/kubeflow-dashboard-operator/issues/213
bumps the `KubeflowDashboardLinks` lib to Patch 3, lib was updated in https://github.com/canonical/kubeflow-dashboard-operator/pull/219
=> chore: bump dashboard links lib

config.yaml
closes #181 
brings in the changes from https://github.com/kubeflow/manifests/tree/v1.9.0
=> chore: bump training operator to v1.8.0

.github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
=> ci(upload-charm): use charmcraft from latest/candidate in track/1.7

tools/get-images.sh
Closes #192.
This PR updates `tools/get-images.sh` to capture images properly. The bash script is updated to look at `config.yaml` instead of `metadata.yaml`, and searches all options that match the regular expression "-image$" (meaning all options that end with "image". to capture the value in the `default` key. Note that in our case only 1 value should be captured, but this way is more robust if more images are added in the future.
=> Update tools/get-images.sh to capture images properly

tools/get-images.sh
This PR is a backport of #193 for track/1.18.
It updates `tools/get-images.sh` to capture the needed images properly. The bash script is updated to look at `config.yaml` instead of `metadata.yaml`, and searches all options that match the regular expression "-image$" (meaning all options that end with "image". to capture the value in the `default` key. Note that in our case only 1 value should be captured, but this way is more robust if more images are added in the future.
=> chore(backport-1.8):  Update tools/get-images.sh to capture images properly

.github/workflows/integrate.yaml, .gitignore, terraform/README.md, terraform/main.tf, terraform/outputs.tf, terraform/variables.tf, terraform/versions.tf, tox.ini
Create a `terraform/` directory that hosts the Terraform module for this charm. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit) and it is follows what was done in canonical/argo-operators#198.
To test the module:
- Clone the repository and switch this PR's branch.
- First run `tox -e tflint` to ensure that linting is correct
- Run `terraform apply -var "channel=latest/edge" -var "model_name=kubeflow" --auto-approve` and wait until the charm is `Active` and `Idle`.
Ref #197
=> feat: Add terraform module

.github/workflows/integrate.yaml, .gitignore, terraform/README.md, terraform/main.tf, terraform/outputs.tf, terraform/variables.tf, terraform/versions.tf, tox.ini
Create a `terraform/` directory that hosts the Terraform module for this charm. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit) and it is follows what was done in canonical/argo-operators#198.
Closes #197
=> feat: Backport terraform module from #200

requirements-fmt.txt, requirements-integration.txt, requirements-lint.txt, requirements-unit.txt, requirements.txt, tests/integration/test_charm.py, tox.ini
* Pin pip to 24.2 due to https://github.com/jazzband/pip-tools/issues/2131
* Update python dependencies using 'tox -e update-requirements'
Ref canonical/bundle-kubeflow#1177
=> chore: update python dependencies + pin pip

requirements-integration.txt, requirements-unit.txt, requirements.txt
This commit pins chisme to >= 0.4.4 to avoid an issue with the metrics endpoint. For more information refer to
canonical/charmed-kubeflow-chisme#124.
=> build: pin chisme to >= 0.4.4 to bring grafana test fixes

.github/workflows/integrate.yaml
The CI was not getting triggered as there was an indentation error in the workflow yaml
https://github.com/canonical/training-operator/actions/runs/16113367531
=> fix: Correct the indentation of integrate.yaml workflow
